import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:learning_flutter/app/layout/index.dart';
import 'package:learning_flutter/app/routes.dart';
import 'package:web_socket_channel/io.dart';
import 'package:flutter_circular_chart/flutter_circular_chart.dart';

final channel =
    IOWebSocketChannel.connect('wss://ws.coincap.io/trades/binance');

class App extends StatelessWidget {
  @override
  Widget build(BuildContext ctx) {
    return new MaterialApp(
      title: 'Learning flutter',
      theme: ThemeData(
        primarySwatch: Colors.orange,
        brightness: Brightness.light,
        fontFamily: 'ChakraPetch',
      ),
      supportedLocales: [const Locale('en'), const Locale('ar')],
      routes: routes,
      // initialRoute: '/',
      home: Scaffold(
        body: Chart(),
        appBar: Toolbar('Home'),
        drawer: Navigation(),
      ),
    );
  }
}

class Autogenerated {
  // String exchange;
  // String base;
  // String quote;
  // String direction;
  double price;
  double volume;
  double timestamp;
  double priceUsd;

  Autogenerated({
    // this.exchange,
    // this.base,
    // this.quote,
    // this.direction,
    this.price,
    this.volume,
    this.timestamp,
    this.priceUsd,
  });

  Autogenerated.fromJson(Map<String, dynamic> json) {
    // exchange = json['exchange'];
    // base = json['base'];
    // quote = json['quote'];
    // direction = json['direction'];
    price = (json['price'] ?? 1) + .0;
    volume = (json['volume'] ?? 1) + .0;
    timestamp = (json['timestamp'] ?? 1) + .0;
    priceUsd = (json['priceUsd'] ?? 1) + .0;
  }

  Map<String, double> toJson() {
    final data = new Map<String, double>();
    // data['exchange'] = this.exchange;
    // data['base'] = this.base;
    // data['quote'] = this.quote;
    // data['direction'] = this.direction;
    data['price'] = this.price;
    data['volume'] = this.volume;
    // data['timestamp'] = this.timestamp;
    data['priceUsd'] = this.priceUsd;
    return data;
  }
}
// double.parse(input.toString());

class Chart extends StatefulWidget {
  @override
  _ChartState createState() => _ChartState();
  // var data = Autogenerated.fromJson({}).toJson();
}

class _ChartState extends State<Chart> {
  @override
  void initState() {
    channel.stream.listen((value) {
      print(value);
      var data = Autogenerated.fromJson(json.decode(value)).toJson();
      _chartKey.currentState.updateData([circularStack(data)]);
      setState(() {});
    }).cancel();
    super.initState();
  }

  final GlobalKey<AnimatedCircularChartState> _chartKey =
      new GlobalKey<AnimatedCircularChartState>();

  @override
  Widget build(BuildContext context) {
    return AnimatedCircularChart(
      key: _chartKey,
      size: const Size(300, 300),
      chartType: CircularChartType.Pie,
      initialChartData: <CircularStackEntry>[
        circularStack(Autogenerated.fromJson({}).toJson()),
      ],
    );
  }
  @override
  void dispose() {
    super.dispose();
  }
}

circularStack(data) {
  return CircularStackEntry(
    [
      CircularSegmentEntry(
        data['price'],
        Colors.red[200],
        rankKey: 'price',

      ),
      CircularSegmentEntry(
        data['volume'],
        Colors.green[200],
        rankKey: 'volume',
      ),
      CircularSegmentEntry(
        data['priceUsd'],
        Colors.yellow[200],
        rankKey: 'priceUsd',
      ),
    ],
  );
}
